import {TransactionStatus} from "./transactions.ts";

export type Property = {
    id: number,
    user_id: number,
    nama: string,
    deskripsi: string,
    tanggal_dibuat: string,
    tanggal_mulai_sewa: string,
    sewa_untuk: "Pria" | "Wanita" | "Campur",
    latitude: string,
    longitude: string,
    kategori: "kost" | "kontrakan",
    provinsi: string,
    kota: string,
    kecamatan: string,
    alamat: string,
    catatan_alamat: string | null,
    fasilitas: "kosongan" | "furnished" | "full-furnished",
    kamar_mandi: number,
    lebar_tanah: number,
    daya_listrik: number,
    sumber_air: "PDAM" | "Sumur",
    total_kamar: number,
    luas_kamar: number,
    total_lemari: number,
    minimum_sewa: number,
    kapasitas_motor: number,
    kapasitas_mobil: number,
    meja: number,
    kasur: number,
    harga_sewa_tahun: number,
    harga_sewa_3_bulan: number,
    harga_sewa_1_bulan: number,
    bank: string,
    rekening: string,
    status: TransactionStatus,
    deleted_at: string | null,
    created_at: string,
    updated_at: string
}

export type PropertyWaterSource = "PDAM" | "Sumur";

export type PropertyFacility =  "kosongan" | "furnished" | "full-furnished";

export type PropertyCategory = "kost" | "kontrakan";

export type PropertyGenderRestriction = "Pria" | "Wanita" | "Campur";

export type PropertyUser = {
    id: number,
    fullname: string,
    gender: number,
    date_of_birth: string,
    phone_number: string,
    job: string | null,
    school_name: string | null,
    city: string | null,
    status: string | null,
    last_education: string | null,
    emergency_contact: string | null,
    photo_profile: string,
    id_card: string,
    id_card_with_person: string | null,
    roles: string,
    email: string,
    email_verified_at: string | null,
    created_at: string,
    updated_at: string,
    pemilik_property: number
}

export type PropertyDetail = {
    id: number,
    user_id: number,
    nama: string,
    deskripsi: string,
    tanggal_dibuat: string,
    tanggal_mulai_sewa: string,
    sewa_untuk: PropertyGenderRestriction,
    latitude: string,
    longitude: string,
    kategori: PropertyCategory,
    provinsi: string,
    kota: string,
    kecamatan: string,
    alamat: string,
    catatan_alamat: string | null,
    fasilitas: PropertyFacility,
    kamar_mandi: number,
    lebar_tanah: number,
    daya_listrik: number,
    sumber_air: PropertyWaterSource,
    total_kamar: number,
    luas_kamar: number,
    total_lemari: number,
    minimum_sewa: number,
    kapasitas_motor: number,
    kapasitas_mobil: number,
    meja: number,
    kasur: number,
    harga_sewa_tahun: number,
    harga_sewa_3_bulan: number,
    harga_sewa_1_bulan: number,
    bank: string,
    rekening: string,
    status: TransactionStatus | null,
    deleted_at: string | null,
    created_at: string,
    updated_at: string,
    image: string[],
    transaction_success: number,
    rules: string[],
    user: PropertyUser[]
}